name: clang-format-lint

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: './src'
        style: file
        clangFormatVersion: 16
